name: Update profile summary cards

on:
  workflow_dispatch:
  schedule:
    - cron: "24 8 * * *"

permissions:
  contents: write

jobs:
  update-cards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_STATS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: main
          UTC_OFFSET: -3
          EXCLUDE: ""
          AUTO_PUSH: true
